autrainer/training/callback_manager.py, poetry.lock, pyproject.toml
This PR removes the callback signature check as type hints as it enforced to type hint the trainer class as a string.
Improved callback signature checks may be reintroduced at a later point in time if they are needed.
Also removes the hardcoded `iso-639` dependency as we can now correctly handle `opensmile` with poetry (for ref see: https://github.com/audeering/audformat/pull/456).
=> Fix Broken Callbacks and Hardcoded Dependencies

README.md, pyproject.toml
Closes #4 by adding the correct link path to the `README.md` and adding a repository and documentation link to the `pyproject.toml`.
=> Fix README Header Image and Add Missing PyPI Links

autrainer/serving/serving.py
When using e.g. a local custom model, `autrainer inference` is unable to load the object, as the Python import path (e.g. `some_model.SomeModel`) can not be resolved by `audobject.from_yaml(...)`.
This is fixed by adding the current working directory to the path.
=> Fix Inference with custom Classes

autrainer/core/scripts/abstract_preprocess_script.py, autrainer/core/scripts/command_line_error.py, autrainer/core/scripts/create_script.py, autrainer/core/scripts/delete_failed_script.py, autrainer/core/scripts/delete_states_script.py, autrainer/core/scripts/fetch_script.py, autrainer/core/scripts/group_script.py, autrainer/core/scripts/inference_script.py, autrainer/core/scripts/list_script.py, autrainer/core/scripts/postprocess_script.py, autrainer/core/scripts/preprocess_script.py, autrainer/core/scripts/show_script.py, autrainer/core/scripts/train_script.py, autrainer/core/scripts/utils.py, autrainer/models/tdnn.py, tests/test_cli_wrapper.py, tests/test_integration.py
Currently all CLI commands that rely on Hydra (fetch, preprocess, train, group) were called in a separate sub process.
This choice was initially made as Hydra does not support google colab / jupyter notebook environments (for ref. see: https://hydra.cc/docs/advanced/compose_api/).
However, in cases where the Python CLI wrapper is used outside of a notebook, spawning separate processes may be less efficient.
This PR checks if the current _autrainer_ command is called in a notebook, and if so spawns a sub process (as before) and if not calls the script directly.
Second, we now ONLY catch CLI usage-related errors if _autrainer_ is run in a notebook (for convenience and brevity the notebook usage resembles the CLI more closely and tries to fail gracefully) and raises exceptions otherwise. …
=> Run Hydra CLI Commands only in Notebook as Subprocess

README.md, README.rst, autrainer/augmentations/__init__.py, autrainer/augmentations/augmentation_wrappers.py, docs/source/modules/augmentations.rst, poetry.lock, pyproject.toml, tests/test_augmentations.py
Closes #10 by adding a `AudiomentationsAugmentation` wrapper around [audiomentations](https://github.com/iver56/audiomentations) and thus moving the [torch-audiomentations](https://github.com/asteroid-team/torch-audiomentations) wrapper to `TorchAudiomentationsAugmentation`.
This gives the user more freedom on choosing audio augmentations, since `torch-audiomentations` does  not (yet) offer full feature parity.
However using `audiomentations` comes at the drawback that all augmentations need to be converted to numpy arrays and back to tensors in the pipeline.
Also added this info to the docstrings of the numpy-based augmentation wrappers.
=> Add Audiomentations Augmentation Wrapper

autrainer-configurations/_autrainer_.yaml, autrainer/core/utils/__init__.py, autrainer/core/utils/hardware.py, autrainer/serving/serving.py, autrainer/training/outputs_tracker.py, autrainer/training/training.py, docs/source/usage/hydra_configurations.rst, tests/test_core_utils.py
Closes #9 and allow for the selection of different devices for training (defaults to `device: cuda:0`).
If the specified device is not available (or valid), automatically falls back to using the CPU and logs out a warning.
This also applies to inference, where this check was previously missed and could fail if a nonexistent device was selected.
Also: During tracking of the outputs, we need to recompute the non-reduced loss as manually summing up the losses in the main training loop leads to a different loss for some reason. This was previously also done on GPU (if available), but is now moved to the CPU.
=> Modularize CUDA-enabled Device Selection

autrainer/training/training.py, autrainer/training/utils.py, docs/source/modules/models.rst, tests/test_integration.py
This adds support for pretraining and subsequent finetuning on different datasets where the number of classes / the output dimension of the model differs.
If the output dimensions of the last layer found in the checkpoint and the current model differ, the weights of the last linear layer are skipped. This also applies to the optimizer state.
If both datasets (and therefore the state dict and model) share the same output dimension, `skip_last_layer: True` skips the last linear layer explicitly.
Previously, we supported a `pretrained` attribute in the  model, optimizer, and scheduler configurations.
These attributes are now all moved to the model configuration, as they should be grouped together, and are specified as follows:
- `model_checkpoint`: The path to the model checkpoint file.
If …
=> Load Model Checkpoints with Arbitrary Output Dimensions

autrainer/core/scripts/inference_script.py, autrainer/serving/model_paths.py, autrainer/serving/serving.py, autrainer/training/training.py, tests/test_cli_wrapper.py, tests/test_serving.py
Closes #20 and additionally exports a `preprocess_file_handler.yaml` and `preprocess_pipeline.yaml` to be used during inference based on the `features_subdir` of the dataset.
If no preprocessing pipeline is used, `preprocess_file_handler.yaml` is the same as `file_handler.yaml`.
During inference `-p` / `preprocess-cfg` is now set to `default`, automatically loading the preprocessing pipeline used during training. If spectrograms were used for training, the user can still pass audio during inference and it is automatically transformed to spectrograms.
However, this can still be deactivated by setting the preprocessing config to `None` to disable preprocessing or to any local / global preprocessing pipeline. This essentially covers the old implementation.
I currently just "re-export" the …
=> Save Preprocessing Pipeline for Inference

autrainer/datasets/utils/target_transforms.py, tests/test_dataset_utils.py
Closes #18 and adds sigmoid activation to the model outputs for multi-label prediction.
=> Fix Multi-Label Classification Threshold

autrainer-configurations/scheduler/StepLR.yaml, autrainer/training/training.py, docs/source/examples/tutorials/LinearWarmUpLR.yaml, docs/source/modules/schedulers.rst
Closes #17 and adds a new `step_frequency` attribute to the scheduler configuration:
- `batch`: called after every batch (default).
- `evaluation`: called after `eval_frequency` iterations.
This way, regardless of the scheduler used, it can be called at the appropriate time.
More advanced schedulers can always be implemented via callbacks.
=> Fix Inconsistent Scheduler Step Call Positions

autrainer/serving/model_paths.py
As mentioned in #19 the local hugging face model path is constructed wrong. This fixes the naming and concatenates the revision instead of creating a sub directory.
=> Fix Hugging Face Model Local Path Directory

autrainer/datasets/utils/file_handlers.py
For inference, we deserialize our yaml files using `audobject.from_yaml()`.
Some of our classes have catch all `**kwargs` in their `__init__` functions, leading to the following try catch block to not throw a type error:
https://github.com/audeering/audobject/blob/2e9e40f5ed1b12b40174eb5984bc2bb0f6ed2dd3/audobject/core/api.py#L82-L96
This way, audobject cannot remove the `_object_root_` attribute created during loading the object, and we have to do it manually for now (only affects classes with `**kwargs` that are serialized with `audobject` for inference).
Maybe there is a better solution in the future.
=> Fix Audio File Handler Deserialization

autrainer/core/scripts/preprocess_script.py
Closes #27 where a OOM error was encountered as too many threads were spawned due to the default being `num_workers = -1`.
It is definitely more safe to have users manually increase the number of threads they want to use, therefore:
- set `num_workers` to 1 by default and checking if they are greater or equal than one, clearly indicate workers == threads
- only perform necessary directory creation calls by filtering first
- improve memory efficiency by explicitly marking the processed data for deletion instead of waiting for the reference to be dropped in the next iteration
=> Fix Preprocessing CLI Defaults and Improve Efficiency

docs/source/examples/tutorials/ESC50-32k.yaml, docs/source/examples/tutorials/esc_50.py, docs/source/modules/datasets.rst, docs/source/usage/tutorials.rst
Closes #28 and provide several improvements of the dataset-related documentation:
- explain the default dataset structure in more detail
- extend the custom datasets tutorial to include a cross-validation example by overriding the `load_dataframes` method
- move runtime arguments note to the datasets documentation
=> Improve Dataset Structure Explanation

docs/source/conf.py, docs/source/usage/cli_reference.rst, docs/source/usage/cli_wrapper.rst
This includes the MIT license in the footer before the authors (in addition to the license badge in the README).
Also fixes a small typo in the docs.
=> Add License to Footer in Documentation

autrainer-configurations/model/Seq-FFNN-IS09.yaml, autrainer-configurations/model/Seq-FFNN-IS10.yaml, autrainer-configurations/model/Seq-FFNN-IS11.yaml, autrainer-configurations/model/Seq-FFNN-IS12.yaml, autrainer-configurations/model/Seq-FFNN-IS13.yaml, autrainer-configurations/model/Seq-FFNN-IS16.yaml, autrainer-configurations/model/Seq-FFNN-eGeMAPS.yaml, autrainer-configurations/model/Whisper-FFNN-Base-T.yaml, autrainer-configurations/model/Whisper-FFNN-Small-T.yaml, autrainer-configurations/model/Whisper-FFNN-Tiny-T.yaml, autrainer-configurations/model/hubert-b-ls960.yaml, autrainer-configurations/model/hubert-l-ll60k.yaml, autrainer-configurations/model/w2v2-b.yaml, autrainer-configurations/model/w2v2-l-100k.yaml, autrainer-configurations/model/w2v2-l-emo.yaml, autrainer-configurations/model/w2v2-l-rob.yaml, autrainer-configurations/model/w2v2-l.yaml, autrainer/models/ast_model.py, autrainer/models/cnn_10.py, autrainer/models/cnn_14.py, autrainer/models/ffnn.py, autrainer/models/sequential.py, autrainer/models/tdnn.py, autrainer/models/w2v2.py, autrainer/models/whisper.py, tests/test_models.py
Closes #40 by removing all Sigmoid and Softmax functions from all models such that the outputs are always raw logits.
=> Remove Optional Sigmoid and Softmax from Models

autrainer/core/scripts/inference_script.py, autrainer/core/scripts/preprocess_script.py, autrainer/serving/serving.py, tests/test_cli_wrapper.py
This adds numerous progress bar improvements:
-  added tqdm progress bars to both `Inference.predict_directory` and `Inference.embed_directory`, controllable via the `-f, --frequency` argument. If set to 0, the progress bar is disabled.
-  merged the `pbar_frequency` and `silent` attributes to `frequency` for `autrainer preprocess` with the same functionality as well such that the CLI and Python wrappers are consistent for all commands / functions.
- adjusted the `frequency` to 1 by default, which should align more with what a user would expect by default.
=> Add Inference Progress Bars

poetry.lock, pyproject.toml
This bumps the [hydra-filter-sweeper](https://github.com/autrainer/hydra-filter-sweeper/) plugin to version `v1.1.0`, allowing to disable logging filtered out configurations (with `log: false`).
=> Bump hydra-filter-sweeper Plugin Version to v1.1.0

autrainer/datasets/abstract_dataset.py, autrainer/datasets/toy_dataset.py, autrainer/datasets/utils/target_transforms/abstract_target_transform.py, autrainer/datasets/utils/target_transforms/label_encoder.py, autrainer/datasets/utils/target_transforms/min_max_scaler.py, autrainer/datasets/utils/target_transforms/multi_label_encoder.py, tests/test_dataset_utils.py, tests/test_datasets.py
Closes #49 by implementing `__len__` for all target transforms.
This also allows to push the `output_dim` property back to the abstract dataset class and simplifies the creation of custom datasets.
=> Add Target Transform Length

autrainer-configurations/dataset/ToyAudio-MTR.yaml, autrainer-configurations/dataset/ToyImage-MTR.yaml, autrainer-configurations/dataset/ToyTabular-MTR.yaml, autrainer/core/constants/training_constants.py, autrainer/datasets/__init__.py, autrainer/datasets/abstract_dataset.py, autrainer/datasets/toy_dataset.py, autrainer/datasets/utils/__init__.py, autrainer/datasets/utils/target_transforms/__init__.py, autrainer/datasets/utils/target_transforms/multi_target_min_max_scaler.py, autrainer/metrics/regression.py, autrainer/training/training.py, docs/source/modules/datasets.rst, docs/source/modules/metrics.rst, tests/test_dataset_utils.py, tests/test_datasets.py, tests/test_integration.py
Closes #48 by adding multi-target regression:
- added new `MultiTargetMinMaxScaler` which applies the `MinMaxScaler` for each target column separately
- added new base dataset
- extended `ToyDataset` to multi-target regression (including configurations)
- extended regression metrics to handle multiple targets by calculating the metric for each target and averaging
=> Add Multi-Target Regression Task

autrainer/metrics/abstract_metric.py, autrainer/metrics/multi_label_classification.py, autrainer/training/outputs_tracker.py, autrainer/training/training.py, autrainer/training/utils.py, tests/test_metrics.py
This closes #57 by introducing a `_safe_f1_score` function that checks for the dimensionality of predictions/labels and overrides the `average` argument if necessary..
When testing this with `ToyTabular-MLC` this resulted in the results being stored in `test_holistic.yaml` being identical to the ones printed at the end of training.
Nevertheless, I want to add some proper tests before merging
=> Fix: safe call to F1 MLC scores

autrainer/models/cnn_14.py
Closes #66 by temporarily adding the missing functions/types to `torch.serialization` globals
=> Fix cnn14 state loading

autrainer/training/outputs_tracker.py, autrainer/training/training.py
This closes #62 by just skipping the initialization of `self.train_tracker` when the results are not exported.
=> Skip and Disable Training Results Tracking if Outputs are not Saved

autrainer/transforms/specific_transforms.py, tests/test_transforms.py
This closes https://github.com/autrainer/autrainer/issues/72 by squeezing the dimensions of the openSMILE feature extraction transform output, as there are unexpected dimensions.
=> Fix openSMILE Feature Extraction Transform Output Shape

autrainer/core/scripts/preprocess_script.py, autrainer/datasets/abstract_dataset.py, autrainer/datasets/aibo.py, autrainer/datasets/dcase_2016_t1.py, autrainer/datasets/dcase_2018_t3.py, autrainer/datasets/dcase_2020_t1a.py, autrainer/datasets/edansa2019.py, autrainer/datasets/emo_db.py, autrainer/datasets/speech_commands.py, autrainer/datasets/utils/dataset_wrapper.py, autrainer/training/training.py, docs/source/modules/transforms.rst, tests/test_datasets.py, tests/test_preprocessing.py
@ramppdev this is a draft PR for changing the underlying dataset. I want your feedback on whether I'm on the right direction before finishing/debugging/testing.
Basically I have done two major changes:
1. Use `@cached_property` for `train_df`, `dev_df`, `test_df`, which defaults to the current structure, but can be overriden if the user doesn't want to change the original format. I also adapted the datasets already which *cannot* be downloaded automatically. For those that can, I have no problem with the original format.ee 
2. Change the `preprocess_script` to *instantiate* the dataset rather than load the CSVs manually, then rely on the `DatasetWrapper` and `torch.utils.data.DataLoader` interfaces for iterating through the data, extracting features, and storing the data
There's probably …
=> Update dataset interface

autrainer/training/training.py, autrainer/training/utils.py, docs/source/modules/training.rst
Closes #60 by adding the missing type annotations and docstrings in the trainer subpackage.
Also fixes a small documentation bug and only exposes the `train()` method of the trainer in the docs as the other ones should be internal.
=> Add Missing Trainer Type Annotations and Docstrings

autrainer/datasets/abstract_dataset.py, tests/test_datasets.py
Closes #59 by adding the missing test for the `BaseMTRegressionDataset` class.
Also, while implementing i noticed a small typo bug in the target transform.
=> Fix Multi-Target Regression Typo and Add Missing MTR Tests

autrainer/datasets/abstract_dataset.py, autrainer/datasets/aibo.py, autrainer/datasets/dcase_2016_t1.py, autrainer/datasets/dcase_2018_t3.py, autrainer/datasets/dcase_2020_t1a.py, autrainer/datasets/edansa2019.py, autrainer/datasets/emo_db.py, autrainer/datasets/speech_commands.py
Small fix reordering the dataset arguments such that `inference_batch_size` comes directly after `batch_size` and `features_path` afterwards.
=> Fix Order of Batch Size and Inference Batch Size Dataset Arguments

autrainer/datasets/abstract_dataset.py, autrainer/datasets/aibo.py, autrainer/datasets/dcase_2016_t1.py, autrainer/datasets/dcase_2018_t3.py, autrainer/datasets/dcase_2020_t1a.py, autrainer/datasets/emo_db.py, autrainer/datasets/toy_dataset.py, autrainer/training/training.py, docs/source/examples/tutorials/esc_50.py, docs/source/modules/datasets.rst, docs/source/usage/tutorials.rst, tests/test_datasets.py
After https://github.com/autrainer/autrainer/pull/54, we ended up with a usable, but pretty weird train, dev, and test dataframe management:
- we added the `train_df`, `dev_df`, and `test_df` properties for the user to overwrite conveniently
- these would then be collected in the `load_dataframes` method of the dataset which we document and tell the user to override for custom datasets, which would now be unnecessary when they overwrite the properties above anyways
- however internally, `load_dataframes` maps to the `df_train`, `df_dev`, and `df_test` attributes which are used throughout autrainer everywhere :D
So this unifies our weird setup, completely removes the `load_dataframes` method, just using the `df_train`, `df_dev`, and `df_test` properties for everything.
Additionally, this …
=> Fix Dataset Dataframe Inconsistencies

autrainer/datasets/abstract_dataset.py
This is a small follow up to https://github.com/autrainer/autrainer/pull/80 where the `get_evaluation_data` method should have been removed.
=> Remove Deprecated Get Evaluation Data Method

autrainer/core/wrappers/instantiate.py, autrainer/criterions/criterion_wrappers.py, autrainer/optimizers/sam.py, autrainer/training/outputs_tracker.py, autrainer/training/training.py, docs/source/examples/optimizer_custom_step.py, docs/source/examples/tutorials/random_scaled_sgd.py, docs/source/modules/criterions.rst, docs/source/modules/optimizers.rst, docs/source/usage/tutorials.rst, tests/test_criterions.py
Closes #84 by ensuring that the `BalancedCrossEntropyLoss` weights sum up to the number of classes.
Draft:
Both the mean-reduced loss and non-reduced loss with a manual mean call are now the same (aside from some small numerical differences introduced through the manual `loss.mean()` call).
This allows us to compute the non-reduced loss during all forward passes directly, and pass these values to the tracker instead of recomputing the per-example losses again.
Let me know if you think it is a good idea to combine the forward calculation and tracking with the non-reduced loss during training.
TODO:
=> Fix Per-Example Loss and Refactor Outputs Tracker

autrainer/core/scripts/preprocess_script.py, autrainer/core/utils/__init__.py, autrainer/core/utils/bookkeeping.py, autrainer/core/utils/hardware.py, autrainer/core/utils/requirements.py, autrainer/training/training.py, tests/test_core_utils.py
This outsources the following I/O related tasks during startup to separate threads to speed up the trainer:
- saving the `requirements.txt`
- generating and saving the model summary
- saving the initial (and initial) best states for the model, optimizer, and scheduler
- saving all audobject YAML files like the model, the target transform, ...
This was a long needed improvement and i measured ~4-6x speedups of the `__init__` function.
=> Speed up Trainer Initialization

autrainer/core/scripts/preprocess_script.py
Quick fix for #92 adding default return `None` when reading features_path in preprocessing.
=> Fix Undefined Features Path in Preprocessing Script

autrainer/core/scripts/inference_script.py, autrainer/serving/model_paths.py
Closes #19 by automatically downloading and allowing to the execution of remote code hosted in a hugging face repository such that users can share custom model implementations that can be used for inference.
Since this is absolutely not safe the option is deactivated by default and we take some security precautions.
If the path to a repo containing custom Python code is specified and `--trust-remote` is not passed, we fail printing the message below and do not download anything. `--trust-remote` also needs to be passed when the model is already downloaded.
```
The Hugging Face repository 'some/remote-repo' likely requires the execution of custom Python code.
To trust the remote repository, pass the '--trust-remote' flag.
Warning: This can be dangerous as it may run arbitrary code on your …
```
=> Support Remote Code for Hugging Face Inference

autrainer/datasets/toy_dataset.py
This fixes a small bug where a dataframe had to be accessed first to set some required parameters, like the proper target column etc.
Since the `super().__init__` call is made with placeholders, this is required to be instantly corrected before the dataset instance is available to the user.
=> Fix ToyDataset Initialization Order

autrainer/core/utils/hardware.py
Small fix that properly handles when torch is not compiled with cuda. If the requested device is not available, a `RuntimeError` is thrown. However, if torch is not compiled with cuda at all, an `AssertionError` is thrown.
=> Fix Device Fallback if not Compiled with Cuda

docs/source/usage/tutorials.rst
Small fix as i forgot to add another tilde to escape as tilde is a special character for sphinx.
=> Fix Unescaped Tilde Character in Plotting Tutorial Docs

autrainer/core/scripts/fetch_script.py
Closes #93 by removing the checkpoint-related attributes from the model configuration which should not be passed to the model as parameters during instantiation (see [model docs](https://autrainer.github.io/autrainer/modules/models.html)).
=> Remove Checkpoint Attributes from Model Config during Fetching

autrainer/core/scripts/preprocess_script.py, tests/test_preprocessing.py
Closes #104 by keeping potential subdirectories in the `features_subdir` / `audio_subdir` of the dataset unchanged during preprocessing.
I think i now understood how the `os.path.basename` call ended up here, the function previously accessed the `DatasetWrapper` dataframe which automatically resolves the file paths on instantiation: https://github.com/autrainer/autrainer/blob/9710ced605df0b6550f85f858fb58ac5a86c359e/autrainer/datasets/utils/dataset_wrapper.py#L58-L62
Therefore i switched to use the (correct) public `df_train` etc. dataframes of the actual dataset class which should have been used in the first place.
Also added test coverage for nested files and improved the readability here and there.
=> Fix Preprocessing Removes Dataset Subdirectories

autrainer/datasets/dcase_2020_t1a.py, docs/extensions/sphinx_lexers.py, docs/source/development/reproducibility_guide.rst, docs/source/examples/quickstart/config_dataset_path.yaml, docs/source/modules/training.rst, docs/source/modules/transforms.rst, docs/source/usage/cli_reference.rst, docs/source/usage/cli_wrapper.rst, docs/source/usage/hydra_configurations.rst, docs/source/usage/quickstart.rst
Closes #81 by outlining the workflow from config creation, over discovery, to overriding local configurations (e.g., with a custom dataset path) in the autrainer quickstart.
Also fixes the following minor bugs:
- `e.g.,` was written without a comma in lots of places
- the lexer for autrainer commands did not handle dashes or equals very well, leading to a change in highlighting
=> Expand Quickstart Docs with List and Show Examples

autrainer/core/utils/__init__.py, autrainer/core/utils/hardware.py, autrainer/training/training.py, tests/test_core_utils.py
This fixes a bug where the main loop goes out of scope and tkinter-related classes are garbage collected / deleted on a different thread by moving explicitly to `Agg` as backend iff a thread could be spawned.
After no thread can be present anymore (manager is a singleton), the backend switches back to whatever it was before to try to clash with user related stuff as little as possible.
For us, switching the backed to `Agg` changes nothing as we produce all plots in a headless fashion anyways.
=> Fix unsafe Matplotlib Backends if Threads are used

autrainer/training/training.py
Disaggregated / stratified evaluation should be performed when either of the two cases is true:
- one or more `data.stratify` columns are present
- `data.target_column` is a list, i.e., we are doing multi-label or multi-target regression, and we want to compute the metrics per class or target
In any other case, we just compute the metrics twice which can be safely avoided by just checking if any of the above cases is present.
=> Fix Redundant Disaggregated Evaluation Calculation

autrainer/transforms/specific_transforms.py, tests/test_transforms.py
Closes #109 by resolving the transform pipeline for all preceding transforms of the `Standardizer`. Thanks to audobject this is very short.
Also adds a shortcut to the `setup` method if the mean and std dev are already calculated to improve performance which can happen if the transform is specified as base for all subsets.
=> Dynamically Resolve Global Standardizer Position

autrainer-configurations/dataset/MSPPodcast-EmoAct-wav.yaml, autrainer-configurations/dataset/MSPPodcast-EmoClass-all-wav.yaml, autrainer-configurations/dataset/MSPPodcast-EmoClass-big4-wav.yaml, autrainer-configurations/dataset/MSPPodcast-EmoDom-wav.yaml, autrainer-configurations/dataset/MSPPodcast-EmoVal-wav.yaml, autrainer/datasets/__init__.py, autrainer/datasets/msppodcast.py, docs/source/modules/datasets.rst, tests/test_datasets.py
Adds MSP-Podcast dataset. As I haven't done that in a while, it would be fantastic if you can have a look @ramppdev 
Additionally, I remove a stray print in `AIBO`. That was only there for debugging.
---
P.S. I am also wondering what's the preferred way for debugging a dataset when developing? For now, I used a `python` script:
```python
from autrainer.datasets.msppodcast import MSPPodcast
data = MSPPodcast(
path="",
index_column="FileName",
target_column="EmoValf",
file_type="wav",
file_handler="autrainer.datasets.utils.AudioFileHandler",
features_subdir="Audios",
metrics=["autrainer.metrics.Accuracy"],
tracking_metric="autrainer.metrics.Accuracy",
batch_size=1,
seed=42,
categories=["A", "H", "N", "S"]
)
train_loader = data.train_loader
print(data.target_transform) …
```
=> Add MSP-Podcast dataset

autrainer/training/training.py
Closes #125 and removes the erroneous `+1` when averaging over the losses for logging.
=> Fix too Small Dev and Test Loss Average during Tracking

autrainer-configurations/_autrainer_.yaml, autrainer-configurations/config.yaml, autrainer-configurations/hydra/callbacks/ConfigDirSnapshot.yaml, autrainer/core/scripts/fetch_script.py, autrainer/core/scripts/group_script.py, autrainer/core/scripts/preprocess_script.py, autrainer/core/scripts/train_script.py, autrainer/core/scripts/utils.py, autrainer/core/utils/hardware.py, autrainer/core/wrappers/config_dir_snapshot.py, autrainer/core/wrappers/main.py
Closes #113 by copying all Hydra related configurations to a temporary directory before launching the runs.
Instead of exposing the `conf` directory (or the one specified with `--config-dir/-cd`), the temporary directory is added to the Hydra directories.
This way, edits to the currently executed configuration no longer have any effect on the actual multirun.
At the same time this also fixes:
- reformatting of main configurations to no longer include placeholder (`???`) paramters; this allows running useful hydra commands that need to compose the config like `autrainer train --info`
- handle incompatible `--config-path/-cp` Hydra argument and fail if this is present
- proper handling of setting matplotlib to `Agg` backend (this got somehow triggered again; i.e., i didnt fix it properly …
=> Fix Mutable Hydra Multirun Configurations

autrainer/training/training.py
This fixes a device mismatch when an optimizer state dict is loaded and its state does not match the device by directly moving the state dict.
=> Fix Incorrect Optimizer Device during State Loading

autrainer/serving/serving.py, tests/test_serving.py
Closes #155 by explicitly excluding empty audios for both prediction and embedding, as the results wont really make sense.
Also forces a single window in case the audio is shorter than the windows size (as suggested in https://github.com/autrainer/autrainer/pull/158). As this may lead to inference errors in the model (e.g., for models like CNN10) this also gracefully handles any errors encountered during the forward pass of a single audio sample.
Missing
=> Fix Inference for Empty or too Short Audios
